DEPS =
    [
        {gen_rets, ".*", {git, "https://github.com/redink-toys/gen_rets.git", {branch, "master"}}},
        {lz4, ".*", {git, "https://github.com/szktty/erlang-lz4.git", {branch, "master"}}}
    ],
NEWDEPS =
    case os:getenv("TEST") of
        "1" ->
            [{task, ".*", {git, "https://github.com/redink-toys/task.git", {branch, "master"}}}
             | DEPS];
        _ ->
            DEPS
    end,
lists:keyreplace(deps, 1, CONFIG, {deps, NEWDEPS}).